---
# in older ansible versions there is no ansible_version defined
- fail: msg="You need at least ansible {{ required_ansible_version }}, sorry."
  when: ansible_version is not defined

- fail: msg="You need at least ansible {{ required_ansible_version }}, sorry."
  when: ansible_version.full | version_compare('{{ required_ansible_version }}', '<=')
