---
- hosts: all
  become: yes
  become_method: sudo

  vars:
    required_ansible_version: 2.3
    nodejs_install_npm_user: root

  roles:
    - role: check-preconditions
    - role: install-java
    - role: install-ansible
    - role: geerlingguy.nodejs
